import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Auth',
    description: 'Generated by create next app'
}

export default function AuthLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <section
            className="min-h-screen flex xs:items-start lg:items-center xs:pt-6 lg:pt-0"
            style={{
                backgroundImage: 'url(/assets/auth-bg.svg)',
                backgroundSize: 'cover'
            }}
        >
            {children}
        </section>
    )
}
