import type { Metadata } from 'next'
import TopBar from '@/@/components/degree-details/top-bar-custom'
import Footer from '@/@/components/global/footer'
import NavBar from '@/@/components/navbar/navbar'
import { Suspense } from 'react'

export const metadata: Metadata = {
    title: 'Degree Details',
    description: 'Generated by create next app'
}

export default function DegreeListLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <section
            style={{
                backgroundImage:
                    'url(/assets/degree-details-top-center.svg), url(/assets/degree-list-footer.svg)',
                backgroundPosition: 'top center, bottom right',
                backgroundRepeat: 'no-repeat, no-repeat',
                backgroundSize: 'contain, contain'
            }}
            className="relative"
        >
            <div className="sticky top-0 z-30">
                <Suspense>
                    <NavBar />
                </Suspense>
            </div>
            {children}
            <Footer />
        </section>
    )
}
